name: Deploy to GitHub Pages

on:
  # Trigger the workflow when you push code to your development branch
  push:
    branches:
      - main  
# Workflow permissions to push build to github pages
permissions:
  contents: write 
  pages: write 
  id-token: write 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This ensures the action has access to the full git history for deployment
          fetch-depth: 0 
          
      - name: Set up Node.js
        # Node.js 20.19+ Required
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm'

      - name: Install dependencies
        run: npm install

        # configure user for the deployment commit
      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build and deploy ðŸš€
        # Run the deploy script we defined in package.json
        run: npm run deploy
        env:
          # This is the secret gh-pages uses to push to the repository
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
